// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFdHbFElhzk8Nsr56l4oH7N2vyRzIgXa8',
    appId: '1:262446997989:android:0b6694ee84fa55216b0f0c',
    messagingSenderId: '262446997989',
    projectId: 'conf-2561d',
    databaseURL: 'https://conf-2561d-default-rtdb.firebaseio.com',
    storageBucket: 'conf-2561d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzkRZhofH-y5o1vgD0GNKgEelFfVnmUYQ',
    appId: '1:262446997989:ios:0140b044cc4c5c9a6b0f0c',
    messagingSenderId: '262446997989',
    projectId: 'conf-2561d',
    databaseURL: 'https://conf-2561d-default-rtdb.firebaseio.com',
    storageBucket: 'conf-2561d.appspot.com',
    androidClientId: '262446997989-ro0pr2cvqf1bj2pesu9lbpqgu2guopo8.apps.googleusercontent.com',
    iosClientId: '262446997989-rpcafrl14sb5hidd585kdgl93ia7bnp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.con',
  );
}
